"""empty message

Revision ID: 0c24e2842727
Revises: 
Create Date: 2023-02-27 11:39:57.415089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c24e2842727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annonymous_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annonymous_user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
