"""empty message

Revision ID: 38e3dcc2cb0a
Revises: bbdacdc23add
Create Date: 2023-04-18 06:23:40.692267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e3dcc2cb0a'
down_revision = 'bbdacdc23add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('clip')

    # ### end Alembic commands ###
