"""empty message

Revision ID: b8ad2493eb1f
Revises: 0c24e2842727
Create Date: 2023-02-27 11:42:13.174930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ad2493eb1f'
down_revision = '0c24e2842727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('maiden_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maiden_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
